server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        add_header Cross-Origin-Embedder-Policy "credentialless";
        add_header Cross-Origin-Opener-Policy "same-origin";
        try_files $uri $uri/ /index.html;

    }
}
