version: "3"

tasks:
  default:
    cmds:
      - go-task --list-all

  debug:
    cmds:
      - flutter run -d chrome --wasm

  profile:
    cmds:
      - flutter run -d chrome --wasm --profile

  buildjson:
    cmds:
      - dart run build_runner build --delete-conflicting-outputs

  watchjson:
    cmds:
      - dart run build_runner watch --delete-conflicting-outputs

  publish:
    cmds:
      - flutter build web --wasm --release --base-href "/europe-holiday-map/"

  build:
    cmds:
      - flutter build web --wasm --release
    sources:
      - lib/
    generates:
      - build/web/

  serve:
    dir: build/web
    cmds:
      - task: build-
      - uv run python -m http.server 44322

  mini:
    dir: assets
    cmds: # Take all json and geosjon and minify via jq
      - |
        files=$(find . | grep json)
        for i in $files; do
          tmpfile=${i}_tmp
          echo "Will minify $i ..."
          cat $i | jq -r tostring > $tmpfile
          mv $tmpfile $i
          echo "Successfully minified $i!"
        done

  expand:
    dir: assets
    cmds: # Take all *.json and minify via jq
      - |
        files=$(find . | grep json)
        for i in $files; do
          tmpfile=${i}_tmp
          echo "Will prettify $i ..."
          cat $i | jq '.' > $tmpfile
          mv $tmpfile $i
        done

  favicon:
    dir: web
    cmds:
      - |
        magick -density 1200 favicon.svg -define icon:auto-resize=32 -colors 256 favicon.ico && \
        magick -density 1200 favicon.svg -resize 180x180 apple-touch-icon.png && \
        magick -density 1200 favicon.svg -resize 512x512 icons/Icon-512.png && \
        magick -density 1200 favicon.svg -resize 192x192 icons/Icon-192.png && \
        magick -density 1200 favicon.svg -resize 512x512 icons/Icon-maskable-512.png && \
        magick -density 1200 favicon.svg -resize 192x192 icons/Icon-maskable-192.png 
