version: "3"

tasks:
  default:
    cmds:
      - go-task --list-all

  debug:
    cmds:
      - flutter run -d chrome

  buildjson:
    cmds:
      - dart run build_runner build --delete-conflicting-outputs

  watchjson:
    cmds:
      - dart run build_runner watch --delete-conflicting-outputs

  build:
    cmds:
      - flutter build web --wasm --release

  serve:
    dir: build/web
    cmds:
      - task: build
      - python -m http.server 44322

  mini:
    dir: assets
    cmds: # Take all json and geosjon and minify via jq
      - |
        files=$(find . | grep json)
        for i in $files; do
          tmpfile=${i}_tmp
          echo "Will minify $i ..."
          cat $i | jq -r tostring > $tmpfile
          mv $tmpfile $i
          echo "Successfully minified $i!"
        done

  expand:
    dir: assets
    cmds: # Take all *.json and minify via jq
      - |
        files=$(find . | grep json)
        for i in $files; do
          tmpfile=${i}_tmp
          echo "Will prettify $i ..."
          cat $i | jq '.' > $tmpfile
          mv $tmpfile $i
        done
